# Generated by Django 3.2.19 on 2023-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=100)),
                ('aadharcard_no', models.CharField(max_length=100)),
                ('aadharcard_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowling Allrounder', 'Bowling Allrounder'), ('Batting Allrounder', 'Batting Allrounder'), ('Wicket-Keeper', 'Wicket-Keeper'), ('Bowler', 'Bowler')], max_length=22)),
                ('Pic_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Batting_style', models.CharField(choices=[('Right Handed Bat', 'Right Handed Bat'), ('Left Handed Bat', 'Left Handed Bat')], max_length=22)),
                ('Bowling_style', models.CharField(choices=[('Right-arm Fast Medium', 'Right-arm Fast Medium'), ('Left-arm Fast Medium', 'Left-arm Fast Medium'), ('Right-arm  Medium', 'Right-arm  Medium'), ('Left-arm  Medium', 'Left-arm  Medium'), ('right-arm legbreak', 'right-arm legbreak'), ('right-arm offbreak', 'right-arm offbreak'), ('Left-arm orthodox', 'Left-arm orthodox'), ('Left-arm chinaman', 'Left-arm chinaman')], max_length=22)),
            ],
            options={
                'verbose_name_plural': 'Player List',
                'unique_together': {('name', 'age')},
            },
        ),
    ]
