# Generated by Django 3.2.19 on 2023-05-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season_Name', models.CharField(max_length=100)),
                ('Maximum_Bid_Point', models.IntegerField()),
                ('Maximum_Players_Per_Team', models.IntegerField()),
                ('Minimum_Players_Per_Team', models.IntegerField()),
                ('Winning_point', models.IntegerField()),
                ('NR_point', models.IntegerField()),
                ('Total_over_Per_Innings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=100)),
                ('Short_Name', models.CharField(max_length=100)),
                ('Team_Logo', models.ImageField(blank=True, null=True, upload_to='Team_Logo/')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.season')),
            ],
            options={
                'verbose_name_plural': 'Team List',
                'unique_together': {('Team_Name', 'Season')},
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowling Allrounder', 'Bowling Allrounder'), ('Batting Allrounder', 'Batting Allrounder'), ('Wicket-Keeper', 'Wicket-Keeper'), ('Bowler', 'Bowler')], max_length=22)),
                ('Batting_style', models.CharField(choices=[('Right Handed Bat', 'Right Handed Bat'), ('Left Handed Bat', 'Left Handed Bat')], max_length=22)),
                ('Bowling_style', models.CharField(choices=[('Right-arm Fast Medium', 'Right-arm Fast Medium'), ('Left-arm Fast Medium', 'Left-arm Fast Medium'), ('Right-arm  Medium', 'Right-arm  Medium'), ('Left-arm  Medium', 'Left-arm  Medium'), ('right-arm legbreak', 'right-arm legbreak'), ('right-arm offbreak', 'right-arm offbreak'), ('Left-arm orthodox', 'Left-arm orthodox'), ('Left-arm chinaman', 'Left-arm chinaman')], max_length=22)),
                ('aadharcard_no', models.CharField(max_length=100)),
                ('aadharcard', models.FileField(upload_to='aadharcard/')),
                ('Profile_Pic', models.ImageField(blank=True, null=True, upload_to='Profile_Pic/')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.season')),
            ],
            options={
                'verbose_name_plural': 'Player List',
                'unique_together': {('mail_id', 'Season')},
            },
        ),
        migrations.CreateModel(
            name='CurrentBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Bid_Point', models.IntegerField()),
                ('Date', models.DateField()),
                ('Player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.playerinfo')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Player_name',)},
            },
        ),
        migrations.CreateModel(
            name='Bid_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Sold_Point', models.IntegerField()),
                ('Date', models.DateField()),
                ('Year', models.IntegerField()),
                ('Player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.playerinfo')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.season')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Player_name', 'Season')},
            },
        ),
        migrations.CreateModel(
            name='Available_Point_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_Point', models.IntegerField()),
                ('Available_Point', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.season')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Team_Name', 'Season')},
            },
        ),
    ]
