# Generated by Django 3.2.19 on 2023-05-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTCC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinfo',
            old_name='Pic_img',
            new_name='Profile_Pic',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='aadharcard_img',
            new_name='aadharcard',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='state',
        ),
    ]
