# Generated by Django 3.2.19 on 2023-05-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTCC', '0002_auto_20230516_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=100)),
                ('Maximum_Bid_Point', models.IntegerField()),
                ('Maximum_Players_Per_Team', models.IntegerField()),
                ('Minimum_Players_Per_Team', models.IntegerField()),
                ('Winning_point', models.IntegerField()),
                ('NR_point', models.IntegerField()),
                ('Total_over_Per_Innings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=100)),
                ('Short_Name', models.CharField(max_length=100)),
                ('Team_Logo', models.ImageField(blank=True, null=True, upload_to='Team_Logo/')),
            ],
            options={
                'verbose_name_plural': 'Team List',
                'unique_together': {('Team_Name',)},
            },
        ),
    ]
