# Generated by Django 3.2.19 on 2023-05-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KTCC', '0004_rename_settings_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Bid_Point', models.IntegerField()),
                ('Date', models.DateField()),
                ('Player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.playerinfo')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Player_name',)},
            },
        ),
        migrations.CreateModel(
            name='Bid_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Sold_Point', models.IntegerField()),
                ('Date', models.DateField()),
                ('Year', models.IntegerField()),
                ('Player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.playerinfo')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.setting')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Player_name', 'Season')},
            },
        ),
        migrations.CreateModel(
            name='Available_Point_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_Point', models.IntegerField()),
                ('Available_Point', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.setting')),
                ('Team_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KTCC.teaminfo')),
            ],
            options={
                'unique_together': {('Team_Name', 'Season')},
            },
        ),
    ]
